# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SoftSigma
email: beatrisvboneva@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just blog about computer science, mathematics and not so geeky
  things like the meaning of life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: beatris_boneva
github_username:  Beatris

# Build settings
markdown: kramdown
